//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcePlannerShowcase.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAvailability
    {
        public System.Guid EmployeeId { get; set; }
        public int Week { get; set; }
        public Nullable<int> Days { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
