//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcePlannerShowcase.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivity
    {
        public System.Guid ProjectId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public int Week { get; set; }
        public Nullable<decimal> Work { get; set; }
        public Nullable<decimal> WeekUtilization { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}
